### ISSUE TITLE
Flexbox is now included by default in Bootstrap 4 (since Alpha 6).

### ISSUE THREAD

**Issue by Taubin** [PacktPublishing/Learning-Bootstrap-4#1]
Flexbox is now included in Bootstrap 4 by default, so it is no longer necessary to update the sass variable on pages 119-125.

This is noted in the [6th Alpha](https://github.com/twbs/bootstrap/releases/tag/v4.0.0-alpha.6) of Bootstrap 4 (now in Beta).  

I'm not sure if the books get update often, but it seems as though the entire section on changing sass to add flexbox can be removed in any future updates.

**Comment by gaurav-packt** [comment]
Thanks for the update.
